[parity]
chain = "spec.json"
base_path = "/home/shicong/local-node-parity/parity1"
[network]
port = 30302
[ui]
port = 8181
interface = "all"
[rpc]
port = 8548
interface = "all"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8181
interface = "all"
[account]
password = ["node2.pwds"]
[mining]
engine_signer = "0x07be7bc2572ca709a7e50d0749f85b66f95d1235"
reseal_on_txs = "none"